# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
#automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages: !include_dir_named include

automation:
- id: show_camera_when_doorbell_pressed
  alias: Show Doorbell camera
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: "home/doorbell"
    # Optional
    payload: "true"
    encoding: "utf-8"
  action:
    - service: browser_mod.navigate
      data:
        navigation_path: /lovelace/doorbell
        deviceId: dashboard
    - service: browser_mod.window_reload
- id: stop_doorbell_camera
  alias: Stop Doorbell camera
  initial_state: 'true'
  trigger:
    platform: mqtt
    topic: "home/doorbell"
    # Optional
    payload: "false"
    encoding: "utf-8"
  action:
    - service: browser_mod.navigate
      data:
        navigation_path: /lovelace/0
        deviceId: dashboard
- id: hangout_modus
  alias: hangout modus
  trigger:
    platform: mqtt
    topic: "home/hang-out"
    # Optional
    payload: "false"
    encoding: "utf-8"

mqtt:
  sensor:
    - name: "car_is_plugged"
      unique_id : car_is_plugged
      state_topic: "homie/homey/kia/evInfo/isPlugged"
    - name: "car_range"
      unique_id : car_range
      state_topic: "homie/homey/kia/range"
      value_template: "{{ value|int }}"
      unit_of_measurement: "km"
    - name: "car_battery_level"
      unique_id : car_battery_level
      state_topic: "homie/homey/kia/evInfo/chargeLevel"
      unit_of_measurement: "%"
    - name: "car_charge_time"
      unique_id : car_charge_time
      state_topic: "homie/homey/kia/evInfo/timeUntilCharged"
    - name: "car_is_charging"
      unique_id : car_is_charging
      state_topic: "homie/homey/kia/evInfo/isCharging"
  switch:
    - name: "Hangout modus"
      unique_id : hangout-modus
      state_topic: "homie/homey/hangout/button"
      command_topic: "homie/homey/hangout/button/set"
      qos: 0
      payload_on: "true"
      payload_off: "false"
      optimistic: false
      retain: true

lovelace:
  mode: yaml
  resources:
    [ { url: /hacsfiles/lovelace-card-mod/card-mod.js,                             type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                       type: module },
      { url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,                 type: module },
      { url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,             type: module },
      { url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js,          type: module },
      { url: /hacsfiles/weather-card/weather-card.js,                              type: module },
      { url: /hacsfiles/config-template-card/config-template-card.js,              type: module },
      { url: /hacsfiles/button-card/button-card.js,                                type: module },
      { url: /hacsfiles/lovelace-state-switch/state-switch.js,                     type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js,                                  type: module },
      { url: /local/style.css,                                                     type: css },
      { url: /local/latofonts.css,                                                 type: css }]


browser_mod:
  devices:
    1842a562-204991ad:
      name: dashboard
      force_stay_awake: true